version: '3'
services:
  plivo-mysql:
    container_name: plivo-mysql
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_DATABASE: sms-service
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
    ports:
    - "3306:3306"
    restart: always
  plivo-redis:
    container_name: plivo-redis
    image: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
  app:
    build: .
    volumes:
    - .:/app
    - ~/.m2:/root/.m2
    working_dir: /app
    ports:
    - 8080:8080
    command: mvn clean spring-boot:run
    depends_on:
    - plivo-mysql
    - plivo-redis
